### ISSUE TITLE
Error when command is unknown

### ISSUE THREAD

**Issue by axin0452** [Aust1n46/VentureChat#14]
paper1.19-24 
waterfall-1.19-496
venturechat-3.4.0
ProtocolLib-build569

When the player input command is unknown, the console will output an error

[00:57:52 INFO]: 123456 issued server command: /123123
[00:57:52 ERROR]: [VentureChat] Unhandled exception occurred in onPacketSending(PacketEvent) for VentureChat
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "coloredMessage" is null
        at mineverse.Aust1n46.chat.listeners.PacketListener.onPacketSending(PacketListener.java:78) ~[【聊天】VentureChat-3.4.0_1.19_patch.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:552) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:95) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:525) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:467) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[【前置】ProtocolLib.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:436) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:383) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2067) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2053) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:2483) ~[paper-1.19.jar:git-Paper-24]
        at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:254) ~[adventure-api-4.11.0.jar:?]
        at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:228) ~[adventure-api-4.11.0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:910) ~[paper-1.19.jar:git-Paper-24]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2376) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2147) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-24]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-24]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-24]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-24]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-24]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-24]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-24]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-24]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[00:57:52 ERROR]: Parameters:
  net.minecraft.network.protocol.game.ClientboundSystemChatPacket@10f25972[
    content=<null>
    b=1
  ]

**Comment by Aust1n46** [comment]
This was fixed in https://www.spigotmc.org/resources/venturechat.771/update?update=461106
