### ISSUE TITLE
paper 1.19 seems not too work

### ISSUE THREAD

**Issue by master861** [Aust1n46/VentureChat#16]
The new version dont work with 1.19 paper:
 Error occurred while enabling VentureChat v3.4.1_1.19_patch (Is it up to date?)
java.lang.NoSuchFieldError: SYSTEM_CHAT
        at mineverse.Aust1n46.chat.utilities.Format.createPacketPlayOutChat(Format.java:439) ~[VentureChat-3.4.1_1.19_patch.jar:?]
        at mineverse.Aust1n46.chat.command.chat.Edit.<init>(Edit.java:24) ~[VentureChat-3.4.1_1.19_patch.jar:?]
        at mineverse.Aust1n46.chat.command.VentureCommandExecutor.initialize(VentureCommandExecutor.java:113) ~[VentureChat-3.4.1_1.19_patch.jar:?]
        at mineverse.Aust1n46.chat.MineverseChat.onEnable(MineverseChat.java:123) ~[VentureChat-3.4.1_1.19_patch.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.jar:git-Paper-32]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper-1.19.jar:git-Paper-32]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-32]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-32]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-32]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-32]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-32]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Endercass** [comment]
Replicated on v3.4.1:
```
Error occurred while enabling VentureChat v3.4.1_1.19_patch (Is it up to date?)
java.lang.NoSuchFieldError: SYSTEM_CHAT
at mineverse.Aust1n46.chat.utilities.Format.createPacketPlayOutChat(Format.java:439) ~[771-v457295__VentureChat.jar:?]
at mineverse.Aust1n46.chat.command.chat.Edit.<init>(Edit.java:24) ~[771-v457295__VentureChat.jar:?]
at mineverse.Aust1n46.chat.command.VentureCommandExecutor.initialize(VentureCommandExecutor.java:113) ~[771-v457295__VentureChat.jar:?]
at mineverse.Aust1n46.chat.MineverseChat.onEnable(MineverseChat.java:123) ~[771-v457295__VentureChat.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.jar:git-Paper-36]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper-1.19.jar:git-Paper-36]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-36]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-36]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-36]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-36]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-36]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Endercass** [comment]
Actually, i just did a bit more testing and if you check [ProtocolLib issue 1651](https://github.com/dmulloy2/ProtocolLib/issues/1651), the fix of downloading a dev version of ProtocolLib will fix venturechat
