### ISSUE TITLE
Hello, please fix <3

### ISSUE THREAD

**Issue by augustuslego** [Aust1n46/VentureChat#2]
`java.lang.NullPointerException: Cannot invoke "net.essentialsx.api.v2.services.discord.DiscordService.sendChatMessage(org.bukkit.entity.Player, String)" because the return value of "org.bukkit.plugin.ServicesManager.load(java.lang.Class)" is null
        at mineverse.Aust1n46.chat.listeners.ChatListener.handleVentureChatEvent(ChatListener.java:515) ~[VentureChat-3.3.2.jar:?]
        at mineverse.Aust1n46.chat.listeners.ChatListener.handleTrueAsyncPlayerChatEvent(ChatListener.java:497) ~[VentureChat-3.3.2.jar:?]
        at mineverse.Aust1n46.chat.listeners.ChatListener$1.run(ChatListener.java:53) ~[VentureChat-3.3.2.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-287]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-287]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-287]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by williamd5** [comment]
What plugin version are you using? What server mod and version? I cannot reproduce this on Paper 1.18.2 with Java 17 and version 3.3.2 of the plugin.

**Comment by Aust1n46** [comment]
(Closing old issues)
