### ISSUE TITLE
console spam

### ISSUE THREAD

**Issue by comonier** [Aust1n46/VentureChat#29]
5:57:43 INFO]: [VentureChat] - Detected Offline UUID!
[15:57:43 INFO]: [VentureChat] - If you are using BungeeCord, make sure you have properly setup IP Forwarding.
[15:57:43 INFO]: [VentureChat] - https://www.spigotmc.org/wiki/bungeecord-ip-forwarding/
[15:57:43 INFO]: [VentureChat] - You can access this wiki page from the log file or just Google it.
[15:57:43 INFO]: [VentureChat] - If you're running a "cracked" server, player data might not be stored properly, and thus, you are on your own.
[15:57:43 INFO]: [VentureChat] - If you run your server in offline mode, you will probably lose your player data when switching to online mode!
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:255)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:517)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
    at org.geysermc.floodgate.inject.bungee.BungeeInjector$BungeeClientToProxyInjectInitializer.channelRead(BungeeInjector.java:139)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
    at me.lucko.bungeeguard.bungee.SpoofedLoginResult.inject(SpoofedLoginResult.java:84)
    ... 55 more
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/connection/LoginResult$Property
    at me.lucko.bungeeguard.bungee.SpoofedLoginResult.<init>(SpoofedLoginResult.java:113)
    at me.lucko.bungeeguard.bungee.SpoofedLoginResultJava9.<init>(SpoofedLoginResultJava9.java:40)
    ... 61 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.connection.LoginResult$Property
    ... 63 more

**Comment by comonier** [comment]
nothing to comment
