### ISSUE TITLE
Plugin VentureChat v3.4.4 generated an exception while executing task 96

### ISSUE THREAD

**Issue by MCDunknown** [Aust1n46/VentureChat#57]
`[04:15:08 WARN]: [VentureChat] Plugin VentureChat v3.4.4 generated an exception while executing task 96                                                  java.lang.NullPointerException: Cannot invoke "mineverse.Aust1n46.chat.api.MineverseChatPlayer.getCurrentChannel()" because "mcp" is null                        at mineverse.Aust1n46.chat.listeners.ChatListener.handleTrueAsyncPlayerChatEvent(ChatListener.java:65) ~[VentureChat-3.4.4.jar:?]                        at mineverse.Aust1n46.chat.listeners.ChatListener$1.run(ChatListener.java:53) ~[VentureChat-3.4.4.jar:?]                                                 at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]                                      at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1632]                             at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1632]             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]                                                                at java.lang.Thread.run(Thread.java:833) ~[?:?]`, tell me what is the problem?

**Comment by Aust1n46** [comment]
Not enough info to debug this.
