### ISSUE TITLE
Error on using Deluxetag PAPI placeholder even if the papi extension is installed

### ISSUE THREAD

**Issue by rish0717** [Aust1n46/VentureChat#58]
[13:51:35 WARN]: [VentureChat] Plugin VentureChat v3.4.4 generated an exception while executing task 4855387
java.lang.NoClassDefFoundError: me/clip/deluxetags/DeluxeTag
        at com.extendedclip.papi.expansion.deluxetags.DeluxeTagsExpansion.onRequest(DeluxeTagsExpansion.java:88) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.2.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setBracketPlaceholders(PlaceholderAPI.java:126) ~[PlaceholderAPI-2.11.2.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setBracketPlaceholders(PlaceholderAPI.java:154) ~[PlaceholderAPI-2.11.2.jar:?]
        at mineverse.Aust1n46.chat.listeners.ChatListener.handleTrueAsyncPlayerChatEvent(ChatListener.java:481) ~[VentureChat-3.4.4.jar:?]
        at mineverse.Aust1n46.chat.listeners.ChatListener$1.run(ChatListener.java:53) ~[VentureChat-3.4.4.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-270]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-270]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.clip.deluxetags.DeluxeTag
        ... 12 more
[13:52:38 INFO]: Villager EntityVillager['Villager'/2190071, uuid='d4002b43-7470-4df9-afc2-55470921cf6f', l='ServerLevel[world]', x=-2693.70, y=63.15, z=3680.88, cpos=[-169, 230], tl=24127, v=true] died, message: 'Villager was squished too much'
[13:53:23 INFO]: Rish0717 issued server command: /tags reload
[13:53:23 INFO]: [DeluxeTags] Using standard hex colors format: #aaFF00
[13:53:30 INFO]: Rish0717 issued server command: /chatreload
[13:53:30 INFO]: [VentureChat] - Config reloaded
[13:53:31 WARN]: [VentureChat] Plugin VentureChat v3.4.4 generated an exception while executing task 4884236
java.lang.NoClassDefFoundError: me/clip/deluxetags/DeluxeTag
        at com.extendedclip.papi.expansion.deluxetags.DeluxeTagsExpansion.onRequest(DeluxeTagsExpansion.java:88) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.2.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setBracketPlaceholders(PlaceholderAPI.java:126) ~[PlaceholderAPI-2.11.2.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setBracketPlaceholders(PlaceholderAPI.java:154) ~[PlaceholderAPI-2.11.2.jar:?]
        at mineverse.Aust1n46.chat.listeners.ChatListener.handleTrueAsyncPlayerChatEvent(ChatListener.java:481) ~[VentureChat-3.4.4.jar:?]
        at mineverse.Aust1n46.chat.listeners.ChatListener$1.run(ChatListener.java:53) ~[VentureChat-3.4.4.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-270]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-270]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.clip.deluxetags.DeluxeTag
        ... 12 more

**Comment by Aust1n46** [comment]
The issue is with DeluxeTag.  Either it's out of date or not being updated anymore.
