### ISSUE TITLE
 Could not pass event PlayerCommandPreprocessEvent to VentureChat v3.3.2

### ISSUE THREAD

**Issue by fadfhkdfga** [Aust1n46/VentureChat#61]
[13:15:08] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to VentureChat v3.3.2
java.lang.NullPointerException: Cannot invoke "mineverse.Aust1n46.chat.api.MineverseChatPlayer.getPlayer()" because "mcp" is null
	at mineverse.Aust1n46.chat.listeners.CommandListener.onPlayerCommandPreprocess(CommandListener.java:43) ~[VentureChat-3.3.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor168.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-388]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.openjdk.nashorn.internal.scripts.Script$Recompilation$258$930A$\^eval\_.CMD(<eval>:37) ~[?:?]
	at org.openjdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:648) ~[JShader-1.1.jar:?]
	at org.openjdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513) ~[JShader-1.1.jar:?]
	at org.openjdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:520) ~[JShader-1.1.jar:?]
	at org.openjdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:187) ~[JShader-1.1.jar:?]
	at org.openjdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:379) ~[JShader-1.1.jar:?]
	at org.openjdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:186) ~[JShader-1.1.jar:?]
	at io.github.wysohn.triggerreactor.core.manager.AbstractJavascriptBasedManager$Evaluable.lambda$evaluate$0(AbstractJavascriptBasedManager.java:159) ~[TriggerReactor-bukkit-latest-3.2.5-Release.jar:?]
	at io.github.wysohn.triggerreactor.core.manager.AbstractJavascriptBasedManager$Evaluable.evaluate(AbstractJavascriptBasedManager.java:169) ~[TriggerReactor-bukkit-latest-3.2.5-Release.jar:?]
	at io.github.wysohn.triggerreactor.core.manager.AbstractExecutorManager$JSExecutor.evaluate(AbstractExecutorManager.java:112) ~[TriggerReactor-bukkit-latest-3.2.5-Release.jar:?]
	at io.github.wysohn.triggerreactor.core.manager.AbstractExecutorManager$JSExecutor.execute(AbstractExecutorManager.java:124) ~[TriggerReactor-bukkit-latest-3.2.5-Release.jar:?]
	at io.github.wysohn.triggerreactor.core.script.interpreter.Interpreter.interpret(Interpreter.java:571) ~[TriggerReactor-bukkit-latest-3.2.5-Release.jar:?]
	at io.github.wysohn.triggerreactor.core.script.interpreter.Interpreter.start(Interpreter.java:488) ~[TriggerReactor-bukkit-latest-3.2.5-Release.jar:?]
	at io.github.wysohn.triggerreactor.core.script.interpreter.Interpreter.startWithContextAndInterrupter(Interpreter.java:200) ~[TriggerReactor-bukkit-latest-3.2.5-Release.jar:?]
	at io.github.wysohn.triggerreactor.core.manager.trigger.Trigger.start(Trigger.java:275) ~[TriggerReactor-bukkit-latest-3.2.5-Release.jar:?]
	at io.github.wysohn.triggerreactor.core.manager.trigger.Trigger$1.call(Trigger.java:230) ~[TriggerReactor-bukkit-latest-3.2.5-Release.jar:?]
	at io.github.wysohn.triggerreactor.core.manager.trigger.Trigger$1.call(Trigger.java:226) ~[TriggerReactor-bukkit-latest-3.2.5-Release.jar:?]
	at io.github.wysohn.triggerreactor.core.manager.trigger.Trigger.startInterpretation(Trigger.java:242) ~[TriggerReactor-bukkit-latest-3.2.5-Release.jar:?]
	at io.github.wysohn.triggerreactor.core.manager.trigger.Trigger.activate(Trigger.java:172) ~[TriggerReactor-bukkit-latest-3.2.5-Release.jar:?]
	at io.github.wysohn.triggerreactor.core.manager.trigger.custom.CustomTrigger.onEvent(CustomTrigger.java:73) ~[TriggerReactor-bukkit-latest-3.2.5-Release.jar:?]
	at io.github.wysohn.triggerreactor.bukkit.manager.trigger.CustomTriggerManager$4.execute(CustomTriggerManager.java:143) ~[TriggerReactor-bukkit-latest-3.2.5-Release.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-388]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.teleport(ServerGamePacketListenerImpl.java:1634) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.dismount(ServerGamePacketListenerImpl.java:1597) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.dismount(ServerGamePacketListenerImpl.java:1593) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.dismountTo(ServerPlayer.java:1436) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.dismountVehicle(LivingEntity.java:2581) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.stopRiding(LivingEntity.java:3494) ~[?:?]
	at net.minecraft.world.entity.player.Player.stopRiding(Player.java:1140) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.stopRiding(ServerPlayer.java:1423) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.stopRiding(ServerPlayer.java:1418) ~[?:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:647) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:602) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2010) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1990) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:755) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:251) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1623) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Llopeando** [comment]
Hi!
The same is happening to us when some player uses the /fill command.

```
[01:22:01 INFO]: Alphasalvatore issued server command: /fill -57 8 -32 -49 8 -31 minecraft:granite
[01:22:01 ERROR]: Could not pass event PlayerCommandPreprocessEvent to VentureChat v3.4.4
java.lang.NullPointerException: Cannot invoke "mineverse.Aust1n46.chat.api.MineverseChatPlayer.getPlayer()" because "mcp" is null
        at mineverse.Aust1n46.chat.listeners.CommandListener.onPlayerCommandPreprocess(CommandListener.java:43) ~[VentureChat-3.4.4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor523.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-386]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2264) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-386]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by 7hatGuyAJ** [comment]
same problem here but  I did just find out its only a venture chat issue and using jadedchat instead cures all my problems.

java.lang.NullPointerException: Cannot invoke "mineverse.Aust1n46.chat.api.MineverseChatPlayer.getPlayer()" because "mcp" is null
at mineverse.Aust1n46.chat.listeners.CommandListener.onPlayerCommandPreprocess(CommandListener.java:43) ~[VentureChat-3.6.0.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1206.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-100]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-100]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-100]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2275) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2259) ~[?:?]
at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-100]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-100]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-100]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-100]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-100]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-100]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-100]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-100]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
