### ISSUE TITLE
Error when VentureChat tries to load.

### ISSUE THREAD

**Issue by Gavins38** [Aust1n46/VentureChat#71]
12:25:49 INFO] [Console]: [VentureChat] - Initializing...
[12:25:49 INFO] [Console]: [VentureChat] - Config not found! Generating file.
[12:25:49 INFO] [Console]: [VentureChat] - Checking for Vault...
[12:25:49 INFO] [Console]: [VentureChat] - Loading player data
[12:25:49 WARN] [ProtocolLib]: Loaded class net.kyori.adventure.text.Component from AntiPopup v5.3 which is not a depend or softdepend of this plugin.
[12:25:49 ERROR] [Minecraft]: Error occurred while enabling VentureChat v3.5.0 (Is it up to date?)
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:289) ~[?:?]
        at mineverse.Aust1n46.chat.utilities.Format.createPacketPlayOutChat(Format.java:453) ~[?:?]
        at mineverse.Aust1n46.chat.command.chat.Edit.<init>(Edit.java:24) ~[?:?]
        at mineverse.Aust1n46.chat.command.VentureCommandExecutor.initialize(VentureCommandExecutor.java:113) ~[?:?]
        at mineverse.Aust1n46.chat.MineverseChat.onEnable(MineverseChat.java:123) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:264) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23163!/:arclight-1.19.2-1.0.1-0550c6cd]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23163!/:arclight-1.19.2-1.0.1-0550c6cd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23163!/:arclight-1.19.2-1.0.1-0550c6cd]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServerMixin.java:525) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23163!/:arclight-1.19.2-1.0.1-0550c6cd]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServerMixin.java:439) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23163!/:arclight-1.19.2-1.0.1-0550c6cd]
        at net.minecraft.server.MinecraftServer.handler$zbj000$arclight$enablePlugins(MinecraftServerMixin.java:2194) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:375) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:300) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:165) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2087) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

I am running VentureChat 3.5.0
and im running ProtocolLib 606

**Comment by 7hatGuyAJ** [comment]
Venture chat is way behind on updates and has been for a very long time you should probably look for an alternative. JadeChat has been promising so far.

**Comment by Gavins38** [comment]
Lin

> Venture chat is way behind on updates and has been for a very long time you should probably look for an alternative. JadeChat has been promising so far.

Link please

**Comment by 7hatGuyAJ** [comment]
https://modrinth.com/plugin/jadedchat

**Comment by Aust1n46** [comment]
Don't advertise on my repo.  If you want support that's fine, but don't link to other projects here.  This isn't the place.

**Comment by Aust1n46** [comment]
I had to lookup the server software you're using and it looks like a modded hybrid server.  I'd recommend testing VentureChat in a sandbox environment with Spigot or Paper first to try and isolate your issue.  I cannot test and guarantee compatibility with every forked version of Spigot.
