### ISSUE TITLE
There is an issue where the connection to the server is terminated when using the latest version of Waterfall.

### ISSUE THREAD

**Issue by happy704** [Aust1n46/VentureChat#91]
There is an issue where the connection to the server is terminated when using the latest version of Waterfall.

**Comment by quiquelhappy** [comment]
I'm also experiencing this

**Comment by Aust1n46** [comment]
Could not reproduce this with Waterfall #542 and the latest Paper for 1.20.2 #203

**Comment by madebygood** [comment]
[01:17:38 ERROR]: java.lang.NoSuchMethodError: 'java.lang.String net.md_5.bungee.protocol.packet.SystemChat.getMessage()'
[01:17:38 ERROR]:       at com.loohp.interactivechat.proxy.bungee.InteractiveChatBungee$3.write(InteractiveChatBungee.java:823)
[01:17:38 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[01:17:38 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[01:17:38 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247)
[01:17:38 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[01:17:38 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[01:17:38 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[01:17:38 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[01:17:38 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[01:17:38 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[01:17:38 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[01:17:38 ERROR]: java.lang.NoSuchMethodError: 'java.lang.String net.md_5.bungee.protocol.packet.SystemChat.getMessage()'
[01:17:38 ERROR]:       at com.loohp.interactivechat.proxy.bungee.InteractiveChatBungee$3.write(InteractiveChatBungee.java:823)
[01:17:38 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[01:17:38 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[01:17:38 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247)
[01:17:38 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[01:17:38 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[01:17:38 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[01:17:38 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[01:17:38 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[01:17:38 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[01:17:38 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)

Same Issue.
