### ISSUE TITLE
Error when joining the server as a new player: java.lang.IllegalArgumentException: Index parameter is not within [0 - 0)

### ISSUE THREAD

**Issue by MarvinKlar** [Aust1n46/VentureChat#98]
When I join the server as a new player I get the followin error in my console:
```
[09:39:51] [Server thread/INFO]: Releee joined the game
[09:39:51] [Server thread/WARN]: java.lang.IllegalArgumentException: Index parameter is not within [0 - 0)
[09:39:51] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.StructureModifier.getField(StructureModifier.java:664)
[09:39:51] [Server thread/WARN]: 	at mineverse.Aust1n46.chat.listeners.PacketListenerLegacyChat.onPacketSending(PacketListenerLegacyChat.java:51)
[09:39:51] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[09:39:51] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[09:39:51] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
[09:39:51] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
[09:39:51] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346)
[09:39:51] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308)
[09:39:51] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433)
[09:39:51] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70)
[09:39:51] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373)
[09:39:51] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343)
[09:39:51] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[09:39:51] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[09:39:51] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.b(NetworkManager.java:294)
[09:39:51] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:258)
[09:39:51] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1900)
[09:39:51] [Server thread/WARN]: 	at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1830)
[09:39:51] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.sendMessage(PlayerList.java:1400)
[09:39:51] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:370)
[09:39:51] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:301)
[09:39:51] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList$$Lambda$8997/0x000000001dc27998.run(Unknown Source)
[09:39:51] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.tick(PlayerConnection.java:307)
[09:39:51] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:399)
[09:39:51] [Server thread/WARN]: 	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:196)
[09:39:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1578)
[09:39:51] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[09:39:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406)
[09:39:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[09:39:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[09:39:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer$$Lambda$3648/0x00000000add8eae0.run(Unknown Source)
[09:39:51] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:883)
[09:39:51] [Server thread/INFO]: Releee[/XXXXXXXXXX:59419] logged in with entity id 169 at ([doggerland]-1776.5, 99.0, 413.5)
```

To Reproduce:
- Install ProtocolLib version v4.7.0
- Install VentureChat 3.6.0
- Start and join the server as a new player

Expected behavior:
I expect this error not to occour.

Thanks for your help!

FYI: ProtocolLib dev said it's this issue is related to VentureChat itself: https://github.com/dmulloy2/ProtocolLib/issues/2624

**Comment by Aust1n46** [comment]
What is the server version?  Not enough info here to reproduce.

**Comment by MarvinKlar** [comment]
`This server is running Paper version git-Paper-84 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5059ada)` | @Aust1n46

**Comment by Aust1n46** [comment]
https://api.papermc.io/v2/projects/paper/versions/1.17.1/builds/84/downloads/paper-1.17.1-84.jar

This is what you're using?  If so, why are you using such an out of date build?

Works fine for me on the latest paper for 1.17.1: https://api.papermc.io/v2/projects/paper/versions/1.17.1/builds/411/downloads/paper-1.17.1-411.jar

Don't have the time right now to downgrade my jdk to be able to run build 84...

I'm also using ProtocolLib 5.11.  Some random snapshot v669.  Never had any issues with ProtocolLib as long as I was using a supported version for my server version.

**Comment by MarvinKlar** [comment]
Worked with the latest Paper version!
